version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mi_blog_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   # Volumen nombrado

volumes:
  db_data: {}   # ← aquí defines el volumen