export { addCarousel, fetchCarousel, updateCarousel, deleteCarousel } from "./Carousel"
export { fetchSections } from "./Sections"
export { fetchAlert, updateAlert } from "./Alert"
export { fetchCalendar, updateCalendar } from "./Calendar"
export { fetchDerechohabiencia, updateDerechohabiencia } from "./Derechohabiencia"
export { fetchAccessCard, addAccessCard, updateAccessCard, deleteAccessCard } from "./AccessCard"