export { homeRoutes } from "./Home"
export { whoWeAreRoutes } from "./WhoWeAre"
export { standardsRoutes } from "./Standards"
export { juristicRoutes } from "./Juristic"
export { downloadsRoutes } from "./Downloads"