export { 
    MAX_TITLE_LENGTH, 
    MAX_DESCRIPTION_LENGTH,
    MAX_ACRONYM_LENGTH,
    MAX_AUTHOR_LENGTH,
    MAX_CODE_LENGTH,
    MAX_NAME_PERSON_LENGTH,
    MAX_YEAR_LENGTH,
    MAX_CODE_MEDICAL_LENGTH
} from "./inputs"