export const standards = [
    { code: "NOM-002-SSA3-2007", validity: "Vigente", title: "Para la organización, funcionamiento e ingeniería sanitaria de los servicios de radioterapia", category: "Radioterapia" },
    { code: "NOM-003-SSA3-2010", validity: "Vigente", title: "Para la práctica de la hemodiálisis", category: "Hemodiálisis" },
    { code: "NOM-004-SSA3-2012", validity: "Vigente", title: "Del expediente clínico", category: "Expediente clínico" },
    { code: "NOM-005-SSA2-1993", validity: "Vigente", title: "De los servicios de planificación familiar", category: "Planificación familiar" },
    { code: "NOM-005-SSA3-2010", validity: "Vigente", title: "Que establece los requisitos mínimos de infraestructura y equipamiento de establecimientos para la atención médica de pacientes ambulatorios", category: "Infraestructura" },
    { code: "NOM-006-SSA2-2013", validity: "Vigente", title: "Para la prevención y control de la tuberculosis", category: "Enfermedades infecciosas" },
    { code: "NOM-006-SSA3-2011", validity: "Vigente", title: "Práctica de la anestesiología", category: "Anestesiología" },
    { code: "NOM-007-SSA2-2016", validity: "Vigente", title: "Para la atención de la mujer durante el embarazo, parto y puerperio, y de la persona recién nacida", category: "Ginecología y obstetricia" },
    { code: "NOM-007-SSA3-2011", validity: "Vigente", title: "Para la organización y funcionamiento de los laboratorios clínicos", category: "Laboratorios clínicos" },
    { code: "NOM-008-SSA3-2010", validity: "Vigente", title: "Para el tratamiento integral del sobrepeso y la obesidad", category: "Nutrición" },
    { code: "NOM-009-SSA2-2013", validity: "Vigente", title: "Promoción de la salud escolar", category: "Salud escolar" },
    { code: "NOM-010-SSA2-2010", validity: "Vigente", title: "Para la prevención y control de la infección por Virus de la Inmunodeficiencia Humana", category: "VIH/SIDA" },
    { code: "NOM-011-SSA2-2011", validity: "Vigente", title: "Para la prevención y control de la rabia humana y en los perros y gatos", category: "Zoonosis" },
    { code: "NOM-013-SSA2-2015", validity: "Vigente", title: "Para la prevención y control de enfermedades bucales", category: "Odontología" },
    { code: "NOM-014-SSA2-1994", validity: "Vigente", title: "Para la prevención, detección, diagnóstico, tratamiento, control y vigilancia epidemiológica del cáncer cérvico uterino", category: "Oncología" },
    { code: "NOM-015-SSA2-2010", validity: "Vigente", title: "Para la prevención, tratamiento y control de la diabetes mellitus", category: "Endocrinología" },
    { code: "NOM-016-SSA2-2012", validity: "Vigente", title: "Para la vigilancia, prevención, control, manejo y tratamiento del cólera", category: "Enfermedades infecciosas" },
    { code: "NOM-017-SSA2-2012", validity: "Vigente", title: "Para la vigilancia epidemiológica", category: "Epidemiología" },
    { code: "NOM-021-SSA2-1994", validity: "Vigente", title: "Para la vigilancia, prevención y control del complejo teniosis/cisticercosis en el primer nivel de atención médica", category: "Enfermedades parasitarias" },
    { code: "NOM-022-SSA2-2012", validity: "Vigente", title: "Para la prevención y control de la brucelosis en el ser humano", category: "Zoonosis" },
    { code: "NOM-024-SSA3-2012", validity: "Vigente", title: "Sistemas de información de registro electrónico para la salud. Intercambio de información en salud.", category: "Tecnologías de la información en salud" },
    { code: "NOM-025-SSA2-2014", validity: "Vigente", title: "Para la prestación de servicios de salud en unidades de atención integral hospitalaria médico‐psiquiátrica", category: "Salud mental" },
    { code: "NOM-027-SSA2-2007", validity: "Vigente", title: "Para la prevención y control de la lepra", category: "Enfermedades infecciosas" },
    { code: "NOM-027-SSA3-2013", validity: "Vigente", title: "Regulación de los servicios de salud. Que establece los criterios de funcionamiento y atención en los servicios de urgencias de los establecimientos para la atención médica.", category: "Servicios de urgencias" },
    { code: "NOM-028-SSA2-2009", validity: "Vigente", title: "Para la prevención, tratamiento y control de las adicciones", category: "Salud mental" },
    { code: "NOM-029-SSA2-1999", validity: "Vigente", title: "Para la vigilancia epidemiológica, prevención y control de la leptospirosis en el humano", category: "Zoonosis" },
    { code: "NOM-030-SSA2-2009", validity: "Vigente", title: "Para la prevención, detección, diagnóstico, tratamiento y control de la hipertensión arterial sistémica", category: "Cardiología" },
    { code: "NOM-031-SSA2-1999", validity: "Vigente", title: "Para la atención a la salud del niño", category: "Pediatría" },
    { code: "NOM-032-SSA2-2010", validity: "Vigente", title: "Para la vigilancia epidemiológica, prevención y control de las enfermedades transmitidas por vector", category: "Epidemiología" },
    { code: "NOM-033-SSA2-2011", validity: "Vigente", title: "Para la vigilancia, prevención y control de la intoxicación por picadura de alacrán", category: "Toxicología" },
    { code: "NOM-034-SSA2-2013", validity: "Vigente", title: "Para la prevención y control de los defectos al nacimiento", category: "Genética" },
    { code: "NOM-035-SSA2-2012", validity: "Vigente", title: "Para la prevención y control de enfermedades en la perimenopausia y postmenopausia de la mujer. Criterios para brindar atención médica", category: "Ginecología" },
    { code: "NOM-035-SSA3-2012", validity: "Vigente", title: "En Materia de Información de Salud", category: "Información en salud" },
    { code: "NOM-036-SSA2-2012", validity: "Vigente", title: "Prevención y control de enfermedades. Aplicación de vacunas, toxoides, faboterápicos (sueros) e inmunoglobulinas en el humano", category: "Vacunación" },
    { code: "NOM-037-SSA2-2012", validity: "Vigente", title: "Para la prevención, tratamiento y control de las dislipidemias", category: "Cardiología" },
    { code: "NOM-038-SSA2-2010", validity: "Vigente", title: "Para la prevención, tratamiento y control de las enfermedades por deficiencia de yodo", category: "Endocrinología" },
    { code: "NOM-039-SSA2-2014", validity: "Vigente", title: "Para la prevención y control de las infecciones de transmisión sexual", category: "Salud sexual" },
    { code: "NOM-040-SSA2-2004", validity: "Vigente", title: "En materia de información en salud", category: "Información en salud" },
    { code: "NOM-041-SSA2-2011", validity: "Vigente", title: "Para la prevención, diagnóstico, tratamiento, control y vigilancia epidemiológica del cáncer de mama", category: "Oncología" },
    { code: "NOM-042-SSA2-2006", validity: "Vigente", title: "Prevención y control de enfermedades. Especificaciones sanitarias para los centros de atención canina", category: "Veterinaria" },
    { code: "NOM-043-SSA2-2012", validity: "Vigente", title: "Servicios básicos de salud. Promoción y educación para la salud en materia alimentaria. Criterios para brindar orientación", category: "Nutrición" },
    { code: "NOM-045-SSA2-2005", validity: "Vigente", title: "Para la vigilancia epidemiológica, prevención y control de las infecciones nosocomiales", category: "Infecciones hospitalarias" },
    { code: "NOM-046-SSA2-2005", validity: "Vigente", title: "Violencia familiar, sexual y contra las mujeres. Criterios para la prevención y atención", category: "Salud pública" },
    { code: "NOM-047-SSA2-2015", validity: "Vigente", title: "Para la atención a la salud del Grupo Etario de 10 a 19 años de edad", category: "Pediatría" },
    { code: "NOM-072-SSA1-2012", validity: "Vigente", title: "Etiquetado de medicamentos y de remedios herbolarios", category: "Farmacología" },
    { code: "NOM-077-SSA1-1994", validity: "Vigente", title: "Que establece las especificaciones sanitarias de los materiales de control (en general) para laboratorios de patología clínica", category: "Laboratorios clínicos" },
    { code: "NOM-078-SSA1-1994", validity: "Vigente", title: "Que establece las especificaciones sanitarias de los estándares de calibración utilizados en las mediciones realizadas en los laboratorios de patología clínica", category: "Laboratorios clínicos" },
    { code: "NOM-087-SEMARNAT-SSA1-2002", validity: "Vigente", title: "Protección Ambiental - Salud Ambiental - Residuos Peligrosos Biológicoinfeccioso - Clasificación y especificaciones de manejo", category: "Medio ambiente" },
    { code: "NOM-197-SSA1-2000", validity: "Vigente", title: "Que establece los requisitos mínimos de infraestructura y equipamiento de hospitales y consultorios de atención médica especializada", category: "Infraestructura" },
    { code: "NOM-220-SSA1-2016", validity: "Vigente", title: "Instalación y operación de la farmacovigilancia", category: "Farmacología" },
    { code: "NOM-240-SSA1-2012", validity: "Vigente", title: "Instalación y operación de la tecnovigilancia", category: "Tecnología en salud" },
    { code: "NOM-253-SSA1-2012", validity: "Vigente", title: "Para la disposición de sangre humana y sus componentes con fines terapéuticos", category: "Transfusión sanguínea" },
];
